#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Feature: Incorporate Human Review Before Coding

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Change to project root
cd /Users/andremikalsen/Documents/Coding/autonomous-coding

# ============================================
# ENVIRONMENT SETUP
# ============================================

echo ""
echo "Setting up Python environment..."

# Check for virtual environment
if [ -d ".venv" ]; then
    source .venv/bin/activate
    echo -e "${GREEN}Activated virtual environment (.venv)${NC}"
elif [ -d "auto-claude/.venv" ]; then
    source auto-claude/.venv/bin/activate
    echo -e "${GREEN}Activated virtual environment (auto-claude/.venv)${NC}"
else
    echo -e "${YELLOW}No virtual environment found. Using system Python.${NC}"
fi

# Verify required files exist
echo ""
echo "Verifying project structure..."

required_files=(
    "auto-claude/run.py"
    "auto-claude/spec_runner.py"
    "auto-claude/ui.py"
    "auto-claude/workspace.py"
)

for file in "${required_files[@]}"; do
    if [ -f "$file" ]; then
        echo -e "  ${GREEN}[OK]${NC} $file"
    else
        echo -e "  ${RED}[MISSING]${NC} $file"
    fi
done

# ============================================
# PATTERN FILES (for reference)
# ============================================

echo ""
echo "Pattern files to reference:"
echo "  - auto-claude/ui.py (MenuOption, select_menu, box, colors)"
echo "  - auto-claude/workspace.py (WorkspaceChoice enum, user menus)"
echo "  - auto-claude/validate_spec.py (ValidationResult dataclass)"
echo "  - auto-claude/linear_updater.py (LinearTaskState load/save pattern)"

# ============================================
# SPEC DIRECTORY
# ============================================

SPEC_DIR=".auto-claude/specs/005-incoporate-human-review-before-coding"

echo ""
echo "Spec directory: $SPEC_DIR"

if [ -f "$SPEC_DIR/spec.md" ]; then
    echo -e "  ${GREEN}[OK]${NC} spec.md exists"
else
    echo -e "  ${RED}[MISSING]${NC} spec.md"
fi

if [ -f "$SPEC_DIR/implementation_plan.json" ]; then
    echo -e "  ${GREEN}[OK]${NC} implementation_plan.json exists"
else
    echo -e "  ${RED}[MISSING]${NC} implementation_plan.json"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "This is a CLI-only feature. No services to start."
echo ""
echo "Test Commands:"
echo "  # Run spec creation (will trigger review checkpoint)"
echo "  python auto-claude/spec_runner.py --task 'Test task' --no-build"
echo ""
echo "  # Run tests after implementation"
echo "  pytest tests/test_review.py -v"
echo ""
echo "  # Check review status for a spec"
echo "  python auto-claude/run.py --spec 005 --review-status"
echo ""
